spring:
    profiles: dev
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@//192.168.49.131:1521/ORCLCDB
        username: ADP
        password: p@ssw0rd123
      
logging:
    level: 
        org:
            springframework:
               transaction: DEBUG
               web:
                   servlet:
                       mvc:
                           method:
                               annotation:
                                   RequestMappingHandlerMapping: TRACE
                        
                                   
#debug: true 
               
               
