server:
    port: 9090

spring:
    profiles:
        active: dev

---

spring:
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    mvc:
        view: 
            prefix: /WEB-INF/jsp/
            suffix: .jsp

mybatis:
    type-aliases-package: com.transglobe.demo.model
