spring:
    profiles: dev
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@10.67.67.17:1521/oratg3
        username: TG002932
        password: Cha67902117